# Generated by Django 4.0.4 on 2022-05-08 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hater_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hates',
            name='hate_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
