# Generated by Django 4.0.4 on 2022-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hater_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hates',
            name='h_body',
            field=models.CharField(max_length=140),
        ),
    ]
