# Generated by Django 4.0.4 on 2022-05-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hater_app', '0002_follower_hater_following_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticism',
            old_name='hate_id',
            new_name='hater_id',
        ),
        migrations.RenameField(
            model_name='criticism',
            old_name='user_id',
            new_name='hates_id',
        ),
        migrations.AlterField(
            model_name='criticism',
            name='c_body',
            field=models.CharField(max_length=140),
        ),
    ]
