# Generated by Django 4.0.4 on 2022-05-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hater_app', '0003_rename_hate_id_criticism_hater_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='haters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('login_name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
