# Generated by Django 4.0.4 on 2022-05-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hater_app', '0004_haters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticism',
            name='hater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hater_app.haters'),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='hates_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hater_app.hate'),
        ),
    ]
