# Generated by Django 4.0.4 on 2022-05-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hater_app', '0005_alter_criticism_hater_id_alter_criticism_hates_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='hates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=120)),
                ('haters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hater_app.haters')),
            ],
        ),
        migrations.RemoveField(
            model_name='criticism',
            name='hater_id',
        ),
        migrations.RemoveField(
            model_name='criticism',
            name='hates_id',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='criticism_id',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='hate_id',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='hater_id',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='hater_being_followed_id',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='hater_following_id',
        ),
        migrations.AddField(
            model_name='criticism',
            name='hater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hater_app.haters'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='criticism',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hater_app.criticism'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='hater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hater_app.haters'),
        ),
        migrations.AddField(
            model_name='follower',
            name='hater_being_followed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='hater_app.haters'),
        ),
        migrations.AddField(
            model_name='follower',
            name='hater_following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='hater_app.haters'),
        ),
        migrations.DeleteModel(
            name='Hate',
        ),
        migrations.AddField(
            model_name='criticism',
            name='hates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hater_app.hates'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='hate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hater_app.hates'),
        ),
    ]
