# Generated by Django 4.0.4 on 2022-05-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hater_app', '0006_hates_remove_criticism_hater_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hates',
            old_name='body',
            new_name='h_body',
        ),
    ]
