# Generated by Django 4.0.4 on 2022-05-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hater_app', '0007_rename_body_hates_h_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticism',
            old_name='hater',
            new_name='haters',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='hater',
            new_name='haters',
        ),
    ]
