# Generated by Django 4.0.4 on 2022-05-04 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hater_app', '0008_rename_hater_criticism_haters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='criticism',
            name='haters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hater_app.user_profile'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='haters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hater_app.user_profile'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='hater_being_followed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='hater_app.user_profile'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='hater_following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='hater_app.user_profile'),
        ),
        migrations.AlterField(
            model_name='hates',
            name='haters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hater_app.user_profile'),
        ),
        migrations.DeleteModel(
            name='haters',
        ),
    ]
