# Generated by Django 4.0.4 on 2022-05-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hater_app', '0009_user_profile_alter_criticism_haters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticism',
            name='haters',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='hater_app.user_profile'),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='hates',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='hater_app.hates'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='criticism',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='hater_app.criticism'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='hate',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='hater_app.hates'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='hater_being_followed',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='hater_app.user_profile'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='hater_following',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='hater_app.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
