# Generated by Django 4.0.4 on 2022-05-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hater_app', '0003_hates_user_profile_remove_criticism_hate_id_and_more'),
        ('hater_app', '0010_alter_criticism_haters_alter_criticism_hates_and_more'),
    ]

    operations = [
    ]
